name: Deploy to cPanel

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Change this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to cPanel
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        port: 21
        script: |
          cd  # Change this to your cPanel directory
          rm -rf *  # Clear existing files (if needed)
          scp -r dist  # Copy build files to cPanel directory
