name: Upload to cPanel

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Zip
      run: zip -r test.zip .

    - name: Execute upload script
      run: |
        lftp -e "set ftp:ssl-allow no; open -u ${{ secrets.CPANEL_USERNAME }},${{ secrets.CPANEL_PASSWORD }} ${{ secrets.CPANEL_HOST }}; put -O . ${{ github.workspace }}/test.zip; bye"
    env:
      CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
      CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
      CPANEL_HOST: ${{ secrets.CPANEL_HOST }}